name: Tests

on: [push, pull_request]

jobs:
  unit-tests:
    name: Unit tests (fast)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install requirements
        run: python -m pip install -r requirements.txt

      - name: Run unit tests
        run: pytest -q tests/unit -k "not integration"
        env:
          PYTHONPATH: ./src

  integration-tests:
    name: Integration tests (Hugging Face Hub)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install full requirements
        run: python -m pip install -r requirements.txt

      - name: Run integration tests
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          PYTHONPATH: ./src
        run: pytest -q -m integration tests/integration
